set(SALAMANDER_SOURCES
  salamander/src/bitmap.cpp
  salamander/src/bugreprt.cpp
  salamander/src/common/dep/bzip2/blocksort.c
  salamander/src/common/dep/bzip2/bzlib.c
  salamander/src/common/dep/bzip2/compress.c
  salamander/src/common/dep/bzip2/crctable.c
  salamander/src/common/dep/bzip2/decompress.c
  salamander/src/common/dep/bzip2/huffman.c
  salamander/src/common/dep/bzip2/internal_e.cpp
  salamander/src/common/dep/bzip2/randtable.c
  salamander/src/cache.cpp
  salamander/src/callstk.cpp
  salamander/src/codetbl.cpp
  salamander/src/color.cpp
  salamander/src/common/allochan.cpp
  salamander/src/common/array.cpp
  salamander/src/common/handles.cpp
  salamander/src/common/heap.cpp
  salamander/src/common/messages.cpp
  salamander/src/common/moore.cpp
  salamander/src/common/multimon.cpp
  salamander/src/common/regexp.cpp
  salamander/src/common/sheets.cpp
  salamander/src/common/str.cpp
  salamander/src/common/strutils.cpp
  salamander/src/common/trace.cpp
  salamander/src/common/winlib.cpp
  salamander/src/common/dep/crypt/aescrypt.c
  salamander/src/common/dep/crypt/aeskey.c
  salamander/src/common/dep/crypt/aestab.c
  salamander/src/common/dep/crypt/fileenc.c
  salamander/src/common/dep/crypt/hmac.c
  salamander/src/common/dep/crypt/pwd2key.c
  salamander/src/common/dep/crypt/sha1.c
  salamander/src/dialogs.cpp
  salamander/src/dialogs2.cpp
  salamander/src/dialogs3.cpp
  salamander/src/dialogs4.cpp
  salamander/src/dialogs5.cpp
  salamander/src/dialogs6.cpp
  salamander/src/dialogse.cpp
  salamander/src/dialogsp.cpp
  salamander/src/drivelst.cpp
  salamander/src/editwnd.cpp
  salamander/src/edtlbwnd.cpp
  salamander/src/execute.cpp
  salamander/src/filesbx1.cpp
  salamander/src/filesbx2.cpp
  salamander/src/filesmap.cpp
  salamander/src/fileswn0.cpp
  salamander/src/fileswn1.cpp
  salamander/src/fileswn2.cpp
  salamander/src/fileswn3.cpp
  salamander/src/fileswn4.cpp
  salamander/src/fileswn5.cpp
  salamander/src/fileswn6.cpp
  salamander/src/fileswn7.cpp
  salamander/src/fileswn8.cpp
  salamander/src/fileswn9.cpp
  salamander/src/fileswna.cpp
  salamander/src/fileswnb.cpp
  salamander/src/filter.cpp
  salamander/src/find.cpp
  salamander/src/finddlg1.cpp
  salamander/src/finddlg2.cpp
  salamander/src/geticon.cpp
  salamander/src/gui.cpp
  salamander/src/icncache.cpp
  salamander/src/iconlist.cpp
  salamander/src/jumplist.cpp
  salamander/src/keyboard.cpp
  salamander/src/logo.cpp
  salamander/src/mainwnd1.cpp
  salamander/src/mainwnd2.cpp
  salamander/src/mainwnd3.cpp
  salamander/src/mainwnd4.cpp
  salamander/src/mainwnd5.cpp
  salamander/src/mapi.cpp
  salamander/src/masks.cpp
  salamander/src/md5.cpp
  salamander/src/menu1.cpp
  salamander/src/menu2.cpp
  salamander/src/menu3.cpp
  salamander/src/menu4.cpp
  salamander/src/menubar.cpp
  salamander/src/msgbox.cpp
  salamander/src/ms_init.cpp
  salamander/src/olespy.cpp
  salamander/src/pack1.cpp
  salamander/src/pack2.cpp
  salamander/src/pack3.cpp
  salamander/src/packac.cpp
  salamander/src/packers.cpp
  salamander/src/plugins1.cpp
  salamander/src/plugins2.cpp
  salamander/src/plugins3.cpp
  salamander/src/plugins4.cpp
  salamander/src/plugins/shared/dbg.cpp
  salamander/src/common/dep/pnglite/pnglite.c
  salamander/src/precomp.cpp
  salamander/src/pwdmngr.cpp
  salamander/src/reglib/src/regcopy.cpp
  salamander/src/reglib/src/reginmem.cpp
  salamander/src/reglib/src/registry.cpp
  salamander/src/reglib/src/regparse.cpp
  salamander/src/regwork.cpp
  salamander/src/safefile.cpp
  salamander/src/salamdr1.cpp
  salamander/src/salamdr2.cpp
  salamander/src/salamdr3.cpp
  salamander/src/salamdr4.cpp
  salamander/src/salamdr5.cpp
  salamander/src/salamdr6.cpp
  salamander/src/salamdr7.cpp
  salamander/src/salbzip2.cpp
  salamander/src/salinflt.cpp
  salamander/src/salmoncl.cpp
  salamander/src/salshlib.cpp
  salamander/src/salzlib.cpp
  salamander/src/shares.cpp
  salamander/src/shellib.cpp
  salamander/src/shellsup.cpp
  salamander/src/shexreg.c
  salamander/src/shiconov.cpp
  salamander/src/snooper.cpp
  salamander/src/sort.cpp
  salamander/src/stswnd.cpp
  salamander/src/svg.cpp
  salamander/src/tabwnd.cpp
  salamander/src/tasklist.cpp
  salamander/src/thumbnl.cpp
  salamander/src/toolbar1.cpp
  salamander/src/toolbar2.cpp
  salamander/src/toolbar3.cpp
  salamander/src/toolbar4.cpp
  salamander/src/toolbar5.cpp
  salamander/src/toolbar6.cpp
  salamander/src/toolbar7.cpp
  salamander/src/toolbar8.cpp
  salamander/src/tooltip.cpp
  salamander/src/versinfo.cpp
  salamander/src/viewer.cpp
  salamander/src/viewer2.cpp
  salamander/src/viewer3.cpp
  salamander/src/worker.cpp
  salamander/src/zip.cpp
  salamander/src/common/dep/zlib/adler32.c
  salamander/src/common/dep/zlib/compress.c
  salamander/src/common/dep/zlib/crc32.c
  salamander/src/common/dep/zlib/deflate.c
  salamander/src/common/dep/zlib/inffast.c
  salamander/src/common/dep/zlib/inflate.c
  salamander/src/common/dep/zlib/inftrees.c
  salamander/src/common/dep/zlib/trees.c
  salamander/src/common/dep/zlib/zutil.c
)

set(SALAMANDER_RC
  salamander/src/salamand.rc
)
