set(SALAMANDER_SOURCES
  src/bitmap.cpp
  src/bugreprt.cpp
  src/common/dep/bzip2/blocksort.c
  src/common/dep/bzip2/bzlib.c
  src/common/dep/bzip2/compress.c
  src/common/dep/bzip2/crctable.c
  src/common/dep/bzip2/decompress.c
  src/common/dep/bzip2/huffman.c
  src/common/dep/bzip2/internal_e.cpp
  src/common/dep/bzip2/randtable.c
  src/cache.cpp
  src/callstk.cpp
  src/codetbl.cpp
  src/color.cpp
  src/common/allochan.cpp
  src/common/array.cpp
  src/common/handles.cpp
  src/common/heap.cpp
  src/common/messages.cpp
  src/common/moore.cpp
  src/common/multimon.cpp
  src/common/regexp.cpp
  src/common/sheets.cpp
  src/common/str.cpp
  src/common/strutils.cpp
  src/common/trace.cpp
  src/common/widepath.cpp
  src/common/winlib.cpp
  src/common/dep/crypt/aescrypt.c
  src/common/dep/crypt/aeskey.c
  src/common/dep/crypt/aestab.c
  src/common/dep/crypt/fileenc.c
  src/common/dep/crypt/hmac.c
  src/common/dep/crypt/pwd2key.c
  src/common/dep/crypt/sha1.c
  src/dialogs.cpp
  src/dialogs2.cpp
  src/dialogs3.cpp
  src/dialogs4.cpp
  src/dialogs5.cpp
  src/dialogs6.cpp
  src/dialogse.cpp
  src/dialogsp.cpp
  src/drivelst.cpp
  src/editwnd.cpp
  src/edtlbwnd.cpp
  src/execute.cpp
  src/filesbx1.cpp
  src/filesbx2.cpp
  src/filesmap.cpp
  src/fileswn0.cpp
  src/fileswn1.cpp
  src/fileswn2.cpp
  src/fileswn3.cpp
  src/fileswn4.cpp
  src/fileswn5.cpp
  src/fileswn6.cpp
  src/fileswn7.cpp
  src/fileswn8.cpp
  src/fileswn9.cpp
  src/fileswna.cpp
  src/fileswnb.cpp
  src/filter.cpp
  src/find.cpp
  src/finddlg1.cpp
  src/finddlg2.cpp
  src/geticon.cpp
  src/gui.cpp
  src/icncache.cpp
  src/iconlist.cpp
  src/jumplist.cpp
  src/keyboard.cpp
  src/logo.cpp
  src/mainwnd1.cpp
  src/mainwnd2.cpp
  src/mainwnd3.cpp
  src/mainwnd4.cpp
  src/mainwnd5.cpp
  src/mapi.cpp
  src/masks.cpp
  src/md5.cpp
  src/menu1.cpp
  src/menu2.cpp
  src/menu3.cpp
  src/menu4.cpp
  src/menubar.cpp
  src/msgbox.cpp
  src/ms_init.cpp
  src/olespy.cpp
  src/pack1.cpp
  src/pack2.cpp
  src/pack3.cpp
  src/packac.cpp
  src/packers.cpp
  src/plugins1.cpp
  src/plugins2.cpp
  src/plugins3.cpp
  src/plugins4.cpp
  src/plugins/shared/dbg.cpp
  src/common/dep/pnglite/pnglite.c
  src/precomp.cpp
  src/pwdmngr.cpp
  src/reglib/src/regcopy.cpp
  src/reglib/src/reginmem.cpp
  src/reglib/src/registry.cpp
  src/reglib/src/regparse.cpp
  src/regwork.cpp
  src/safefile.cpp
  src/salamdr1.cpp
  src/salamdr2.cpp
  src/salamdr3.cpp
  src/salamdr4.cpp
  src/salamdr5.cpp
  src/salamdr6.cpp
  src/salamdr7.cpp
  src/salbzip2.cpp
  src/salinflt.cpp
  src/salmoncl.cpp
  src/salshlib.cpp
  src/salzlib.cpp
  src/shares.cpp
  src/shellib.cpp
  src/shellsup.cpp
  src/shexreg.c
  src/shiconov.cpp
  src/snooper.cpp
  src/sort.cpp
  src/stswnd.cpp
  src/svg.cpp
  src/tabwnd.cpp
  src/tasklist.cpp
  src/thumbnl.cpp
  src/toolbar1.cpp
  src/toolbar2.cpp
  src/toolbar3.cpp
  src/toolbar4.cpp
  src/toolbar5.cpp
  src/toolbar6.cpp
  src/toolbar7.cpp
  src/toolbar8.cpp
  src/tooltip.cpp
  src/versinfo.cpp
  src/viewer.cpp
  src/viewer2.cpp
  src/viewer3.cpp
  src/worker.cpp
  src/zip.cpp
  src/common/dep/zlib/adler32.c
  src/common/dep/zlib/compress.c
  src/common/dep/zlib/crc32.c
  src/common/dep/zlib/deflate.c
  src/common/dep/zlib/inffast.c
  src/common/dep/zlib/inflate.c
  src/common/dep/zlib/inftrees.c
  src/common/dep/zlib/trees.c
  src/common/dep/zlib/zutil.c
)

set(SALAMANDER_RC
  src/salamand.rc
)
