// SPDX-FileCopyrightText: 2023 Open Salamander Authors
// SPDX-FileCopyrightText: 2026 Sally Authors
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// C__Messages holds a C__StringStreamBuf and a C__TraceStream by value, so this
// header cannot be parsed without trace.h. src/precomp.h happened to include
// trace.h first and hid that for years; tserver's precomp.h does not, and its
// .cpp files include messages.h directly. Release never noticed either, because
// it defines MESSAGES_DISABLE (CMakeLists.txt) and skips this entire body - so
// the break only appeared in Debug, in one utility nobody builds that way.
#include "trace.h"

// THE choke point for every message box Sally's diagnostic layer raises.
//
// In the shipping app the W entry is ::MessageBoxW. The A entry is a compatibility
// adapter for legacy diagnostic byte streams and decodes once into the W entry.
//
// In a TEST BINARY (SALLY_NO_INTERACTIVE_DIALOGS, set tree-wide by
// tests/CMakeLists.txt so every target gets it however it is declared, or
// SALLY_E2E_HOST; never on sally.exe) they print to stderr and return a
// non-escalating answer instead of
// blocking, because nothing is there to click OK and the run would hang FOREVER:
// no crash, no timeout, no output. That is not hypothetical - it cost two full
// diagnosis cycles on CFindDialog, each ended only by
// attaching cdb to the stuck process.
//
// EVERY diagnostic message box must go through here. A direct ::MessageBox call
// in diagnostic code re-opens the hazard - that is exactly how handles.cpp:578
// survived the first version of this fix and hung the run a third time.
// Declared outside the MESSAGES_DISABLE guard: the hazard exists either way.
int __MessagesShowA(HWND hWnd, const char* text, const char* caption, UINT uType);
int __MessagesShowW(HWND hWnd, const WCHAR* text, const WCHAR* caption, UINT uType);

// TRUE when this process must never block on a human. Exposed because the message
// box is not the only way a diagnostic can hang an automated run: see the
// ConnectToTraceServer() calls in C__Handles::~C__Handles, which wait on a named
// pipe during static destruction.
bool __MessagesIsNonInteractive();

// macro MESSAGES_DISABLE - disconnect module from compilation
// macro MESSAGES_DEBUG - print file + line numbers before message + enable messages displayed via DMESSAGE_???
// macro MULTITHREADED_MESSAGES_ENABLE - prepare messages for multithreaded applications

#ifndef MESSAGES_DISABLE

#ifdef MULTITHREADED_MESSAGES_ENABLE

// ensures access to module functions and data for current thread
void EnterMessagesModul();
// call when current thread no longer needs access to module functions and data
void LeaveMessagesModul();

#endif // MULTITHREADED_MESSAGES_ENABLE

/// returns pointer to global buffer, which fills the string from resource
const char* rsc(int resID);
const WCHAR* rscW(int resID);

/// returns pointer to global buffer, which fills the string from sprintf
const char* spf(const char* formatString, ...);
const WCHAR* spfW(const WCHAR* formatString, ...);

/// returns pointer to global buffer, which fills the string from sprintf
const char* spf(int formatStringResID, ...);
const WCHAR* spfW(int formatStringResID, ...);

/// returns pointer to global buffer, which fills the string with error description
const char* err(DWORD error);
const WCHAR* errW(DWORD error);

extern const char* __MessagesTitle;
extern const WCHAR* __MessagesTitleW;
extern HWND __MessagesParent;
extern HINSTANCE HInstance; // expected variable with instance handle

/// Set title of messagebox generated by macros MESSAGExx. A process-lifetime copy
/// is made for both the UTF-16 owner and the legacy diagnostic projection.
void SetMessagesTitleW(const WCHAR* title);

/// Constructs every process-lifetime diagnostic owner in this module up front.
/// They are deliberately never freed (see the note on the storage accessors), so the
/// heap leak checker in common/heap.cpp calls this BEFORE its start checkpoint - otherwise
/// whichever of them happens to be touched first during the session is reported as a leak
/// on every debug exit. Idempotent; safe to call more than once.
void PreallocateMessagesDiagnosticStorage();

/// Set parent of messagebox generated by macros MESSAGExx
void SetMessagesParent(HWND parent);

class C__Messages
{
protected:
    C__StringStreamBuf MessagesStringBuf; // string buffer holding messages stream data
    C__TraceStream MessagesStrStream;     // actual messages stream

public:
    C__Messages();
#ifdef MULTITHREADED_MESSAGES_ENABLE
    ~C__Messages();
#endif // MULTITHREADED_MESSAGES_ENABLE

    C__TraceStream& OStream()
    {
        return MessagesStrStream;
    }

    int MessageBoxT(const char* lpCaption, // address of title of message box
                    UINT uType);           // style of message box

    int MessageBox(HWND hWnd,             // handle of owner window
                   const char* lpCaption, // address of title of message box
                   UINT uType);           // style of message box
};

class C__MessagesW
{
protected:
    C__StringStreamBufW MessagesStringBuf; // string buffer holding messages stream data
    C__TraceStreamW MessagesStrStream;     // actual messages stream

public:
    C__MessagesW();

    C__TraceStreamW& OStream() { return MessagesStrStream; }

    int MessageBoxT(const WCHAR* lpCaption, // address of title of message box
                    UINT uType);            // style of message box

    int MessageBox(HWND hWnd,              // handle of owner window
                   const WCHAR* lpCaption, // address of title of message box
                   UINT uType);            // style of message box
};

extern C__Messages __Messages;
extern C__MessagesW __MessagesW;

/**@name Macros generating messageboxes.
 * if macro MESSAGES_DEBUG is defined, file and line number are displayed
 * on the first line in messageboxes where MESSAGExx is used in code\\
 *
 */

#ifdef MESSAGES_DEBUG

#ifndef MULTITHREADED_MESSAGES_ENABLE

/** displays messagebox with specified text, not in new thread, distributes message
    to calling thread */
#define MESSAGE(parent, str, buttons) \
    (__Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", __Messages.OStream() << str, \
     __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (__MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

/** displays messagebox with specified text, in new thread, does not distribute message
    to calling thread */
#define MESSAGE_T(str, buttons) \
    (__Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", __Messages.OStream() << str, \
     __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (__MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#else // MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", \
     __Messages.OStream() << str, __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", \
     __MessagesW.OStream() << str, __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", \
     __Messages.OStream() << str, __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", \
     __MessagesW.OStream() << str, __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#endif // MULTITHREADED_MESSAGES_ENABLE

#else // MESSAGES_DEBUG

#ifndef MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (__Messages.OStream() << str, __Messages).MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (__MessagesW.OStream() << str, __MessagesW).MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (__Messages.OStream() << str, __Messages).MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (__MessagesW.OStream() << str, __MessagesW).MessageBoxT(__MessagesTitleW, (buttons))

#else // MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << str, \
     __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), \
                    __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), \
                    __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << str, \
     __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#endif // MULTITHREADED_MESSAGES_ENABLE

#endif // MESSAGES_DEBUG

/** displays messagebox with specified text and info icon, not in new
    thread, distributes message to calling thread */
#define MESSAGE_I(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONINFORMATION | (buttons))

#define MESSAGE_IW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONINFORMATION | (buttons))

/** displays messagebox with specified text and question icon, not in new
    thread, distributes message to calling thread */
#define MESSAGE_Q(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONQUESTION | (buttons))

#define MESSAGE_QW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONQUESTION | (buttons))

/** displays messagebox with specified text and error icon, not in new
    thread, distributes message to calling thread */
#define MESSAGE_E(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONEXCLAMATION | (buttons))

#define MESSAGE_EW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONEXCLAMATION | (buttons))

/** displays messagebox with specified text and info icon, in new thread,
    does not distribute message to calling thread */
#define MESSAGE_TI(str, buttons) \
    MESSAGE_T(str, MB_ICONINFORMATION | (buttons))

#define MESSAGE_TIW(str, buttons) \
    MESSAGE_TW(str, MB_ICONINFORMATION | (buttons))

/** displays messagebox with specified text and question icon, in new thread,
    does not distribute message to calling thread */
#define MESSAGE_TQ(str, buttons) \
    MESSAGE_T(str, MB_ICONQUESTION | (buttons))

#define MESSAGE_TQW(str, buttons) \
    MESSAGE_TW(str, MB_ICONQUESTION | (buttons))

/** displays messagebox with specified text and error icon, in new thread,
    does not distribute message to calling thread */
#define MESSAGE_TE(str, buttons) \
    MESSAGE_T(str, MB_ICONEXCLAMATION | (buttons))

#define MESSAGE_TEW(str, buttons) \
    MESSAGE_TW(str, MB_ICONEXCLAMATION | (buttons))

#ifdef MESSAGES_DEBUG

/// MESSAGE_I dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_I(parent, str, buttons) MESSAGE_I(parent, str, (buttons))
#define DMESSAGE_IW(parent, str, buttons) MESSAGE_IW(parent, str, (buttons))

/// MESSAGE_Q dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_Q(parent, str, buttons) MESSAGE_Q(parent, str, (buttons))
#define DMESSAGE_QW(parent, str, buttons) MESSAGE_QW(parent, str, (buttons))

/// MESSAGE_E dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_E(parent, str, buttons) MESSAGE_E(parent, str, (buttons))
#define DMESSAGE_EW(parent, str, buttons) MESSAGE_EW(parent, str, (buttons))

/// MESSAGE_TI dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_TI(str, buttons) MESSAGE_TI(str, (buttons))
#define DMESSAGE_TIW(str, buttons) MESSAGE_TIW(str, (buttons))

/// MESSAGE_TQ dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_TQ(str, buttons) MESSAGE_TQ(str, (buttons))
#define DMESSAGE_TQW(str, buttons) MESSAGE_TQW(str, (buttons))

/// MESSAGE_E dependent on existence of macro MESSAGES_DEBUG
#define DMESSAGE_TE(str, buttons) MESSAGE_TE(str, (buttons))
#define DMESSAGE_TEW(str, buttons) MESSAGE_TEW(str, (buttons))

#else // MESSAGES_DEBUG

// to avoid issues with semicolons in the macros defined below
inline int __MessagesEmptyFunction() { return 0; }

#define DMESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#endif // MESSAGES_DEBUG

#else // MESSAGES_DISABLE

// to avoid issues with semicolons in the macros defined below
inline int __MessagesEmptyFunction() { return 0; }

#define EnterMessagesModul() __MessagesEmptyFunction()
#define LeaveMessagesModul() __MessagesEmptyFunction()

/* these functions must report a compilation error
const char *rsc(int resID);
const WCHAR *rscW(int resID);
const char *spf(const char *formatString, ...);
const WCHAR *spfW(const WCHAR *formatString, ...);
const char *spf(int formatStringResID, ...);
const WCHAR *spfW(int formatStringResID, ...);
const char *err(DWORD error);
const WCHAR *errW(DWORD error);
*/

#define SetMessagesTitleW(title) __MessagesEmptyFunction()
#define SetMessagesParent(parent) __MessagesEmptyFunction()
#define PreallocateMessagesDiagnosticStorage() __MessagesEmptyFunction()

#define MESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#define DMESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#endif // MESSAGES_DISABLE
